outputHistograms = [
    {  "type": r.TH1I, "name": "upperCounters"},
    {  "type": r.TH1I, "name": "lowerCounters"},
    {  "type": r.TH1F, "name": "looseMuMinusChi2"},
    {  "type": r.TH1F, "name": "looseMuUpperMinusChi2"},
    {  "type": r.TH1F, "name": "looseMuPlusChi2"},
    {  "type": r.TH1F, "name": "looseMuUpperPlusChi2"},
    {  "type": r.TH1F, "name": "looseMuLowerMinusChi2"},
    {  "type": r.TH1F, "name": "looseMuLowerPlusChi2"},
    {  "type": r.TH1F, "name": "looseMuMinusNdof"},
    {  "type": r.TH1F, "name": "looseMuUpperMinusNdof"},
    {  "type": r.TH1F, "name": "looseMuPlusNdof"},
    {  "type": r.TH1F, "name": "looseMuUpperPlusNdof"},
    {  "type": r.TH1F, "name": "looseMuLowerMinusNdof"},
    {  "type": r.TH1F, "name": "looseMuLowerPlusNdof"},
    {  "type": r.TH1F, "name": "looseMuMinusCharge"},
    {  "type": r.TH1F, "name": "looseMuUpperMinusCharge"},
    {  "type": r.TH1F, "name": "looseMuPlusCharge"}, #;1, "name"looseMuPlusCharge
    {  "type": r.TH1F, "name": "looseMuUpperPlusCharge"}, #;1, "name"looseMuUpperPlusCharge
    {  "type": r.TH1F, "name": "looseMuLowerMinusCharge"}, #;1, "name"looseMuLowerMinusCharge
    {  "type": r.TH1F, "name": "looseMuLowerPlusCharge"}, #;1, "name"looseMuLowerPlusCharge
    {  "type": r.TH1F, "name": "looseMuMinusCurve"}, #;1, "name"looseMuMinusCurve
    {  "type": r.TH1F, "name": "looseMuUpperMinusCurve"}, #;1, "name"looseMuUpperMinusCurve
    {  "type": r.TH1F, "name": "looseMuPlusCurve"}, #;1, "name"looseMuPlusCurve
    {  "type": r.TH1F, "name": "looseMuUpperPlusCurve"}, #;1, "name"looseMuUpperPlusCurve
    {  "type": r.TH1F, "name": "looseMuLowerMinusCurve"}, #;1, "name"looseMuLowerMinusCurve
    {  "type": r.TH1F, "name": "looseMuLowerPlusCurve"}, #;1, "name"looseMuLowerPlusCurve
    {  "type": r.TH1F, "name": "looseMuMinusDxy"}, #;1, "name"looseMuMinusDxy
    {  "type": r.TH1F, "name": "looseMuUpperMinusDxy"}, #;1, "name"looseMuUpperMinusDxy
    {  "type": r.TH1F, "name": "looseMuPlusDxy"}, #;1, "name"looseMuPlusDxy
    {  "type": r.TH1F, "name": "looseMuUpperPlusDxy"}, #;1, "name"looseMuUpperPlusDxy
    {  "type": r.TH1F, "name": "looseMuLowerMinusDxy"}, #;1, "name"looseMuLowerMinusDxy
    {  "type": r.TH1F, "name": "looseMuLowerPlusDxy"}, #;1, "name"looseMuLowerPlusDxy
    {  "type": r.TH1F, "name": "looseMuMinusDz"}, #;1, "name"looseMuMinusDz
    {  "type": r.TH1F, "name": "looseMuUpperMinusDz"}, #;1, "name"looseMuUpperMinusDz
    {  "type": r.TH1F, "name": "looseMuPlusDz"}, #;1, "name"looseMuPlusDz
    {  "type": r.TH1F, "name": "looseMuUpperPlusDz"}, #;1, "name"looseMuUpperPlusDz
    {  "type": r.TH1F, "name": "looseMuLowerMinusDz"}, #;1, "name"looseMuLowerMinusDz
    {  "type": r.TH1F, "name": "looseMuLowerPlusDz"}, #;1, "name"looseMuLowerPlusDz
    {  "type": r.TH1F, "name": "looseMuMinusPixelHits"}, #;1, "name"looseMuMinusPixelHits
    {  "type": r.TH1F, "name": "looseMuUpperMinusPixelHits"}, #;1, "name"looseMuUpperMinusPixelHits
    {  "type": r.TH1F, "name": "looseMuPlusPixelHits"}, #;1, "name"looseMuPlusPixelHits
    {  "type": r.TH1F, "name": "looseMuUpperPlusPixelHits"}, #;1, "name"looseMuUpperPlusPixelHits
    {  "type": r.TH1F, "name": "looseMuLowerMinusPixelHits"}, #;1, "name"looseMuLowerMinusPixelHits
    {  "type": r.TH1F, "name": "looseMuLowerPlusPixelHits"}, #;1, "name"looseMuLowerPlusPixelHits
    {  "type": r.TH1F, "name": "looseMuMinusTrackerHits"}, #;1, "name"looseMuMinusTrackerHits
    {  "type": r.TH1F, "name": "looseMuUpperMinusTrackerHits"}, #;1, "name"looseMuUpperMinusTrackerHits
    {  "type": r.TH1F, "name": "looseMuPlusTrackerHits"}, #;1, "name"looseMuPlusTrackerHits
    {  "type": r.TH1F, "name": "looseMuUpperPlusTrackerHits"}, #;1, "name"looseMuUpperPlusTrackerHits
    {  "type": r.TH1F, "name": "looseMuLowerMinusTrackerHits"}, #;1, "name"looseMuLowerMinusTrackerHits
    {  "type": r.TH1F, "name": "looseMuLowerPlusTrackerHits"}, #;1, "name"looseMuLowerPlusTrackerHits
    {  "type": r.TH1F, "name": "looseMuMinusMuonStationHits"}, #;1, "name"looseMuMinusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuUpperMinusMuonStationHits"}, #;1, "name"looseMuUpperMinusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuPlusMuonStationHits"}, #;1, "name"looseMuPlusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuUpperPlusMuonStationHits"}, #;1, "name"looseMuUpperPlusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuLowerMinusMuonStationHits"}, #;1, "name"looseMuLowerMinusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuLowerPlusMuonStationHits"}, #;1, "name"looseMuLowerPlusMuonStationHits
    {  "type": r.TH1F, "name": "looseMuMinusValidHits"}, #;1, "name"looseMuMinusValidHits
    {  "type": r.TH1F, "name": "looseMuUpperMinusValidHits"}, #;1, "name"looseMuUpperMinusValidHits
    {  "type": r.TH1F, "name": "looseMuPlusValidHits"}, #;1, "name"looseMuPlusValidHits
    {  "type": r.TH1F, "name": "looseMuUpperPlusValidHits"}, #;1, "name"looseMuUpperPlusValidHits
    {  "type": r.TH1F, "name": "looseMuLowerMinusValidHits"}, #;1, "name"looseMuLowerMinusValidHits
    {  "type": r.TH1F, "name": "looseMuLowerPlusValidHits"}, #;1, "name"looseMuLowerPlusValidHits
    {  "type": r.TH1F, "name": "looseMuMinusMatchedMuonStations"}, #;1, "name"looseMuMinusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuUpperMinusMatchedMuonStations"}, #;1, "name"looseMuUpperMinusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuPlusMatchedMuonStations"}, #;1, "name"looseMuPlusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuUpperPlusMatchedMuonStations"}, #;1, "name"looseMuUpperPlusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuLowerMinusMatchedMuonStations"}, #;1, "name"looseMuLowerMinusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuLowerPlusMatchedMuonStations"}, #;1, "name"looseMuLowerPlusMatchedMuonStations
    {  "type": r.TH1F, "name": "looseMuMinusPtError"}, #;1, "name"looseMuMinusPtError
    {  "type": r.TH1F, "name": "looseMuUpperMinusPtError"}, #;1, "name"looseMuUpperMinusPtError
    {  "type": r.TH1F, "name": "looseMuPlusPtError"}, #;1, "name"looseMuPlusPtError
    {  "type": r.TH1F, "name": "looseMuUpperPlusPtError"}, #;1, "name"looseMuUpperPlusPtError
    {  "type": r.TH1F, "name": "looseMuLowerMinusPtError"}, #;1, "name"looseMuLowerMinusPtError
    {  "type": r.TH1F, "name": "looseMuLowerPlusPtError"}, #;1, "name"looseMuLowerPlusPtError
    {  "type": r.TH1F, "name": "looseMuMinusPtRelErr"}, #;1, "name"looseMuMinusPtRelErr
    {  "type": r.TH1F, "name": "looseMuUpperMinusPtRelErr"}, #;1, "name"looseMuUpperMinusPtRelErr
    {  "type": r.TH1F, "name": "looseMuPlusPtRelErr"}, #;1, "name"looseMuPlusPtRelErr
    {  "type": r.TH1F, "name": "looseMuUpperPlusPtRelErr"}, #;1, "name"looseMuUpperPlusPtRelErr
    {  "type": r.TH1F, "name": "looseMuLowerMinusPtRelErr"}, #;1, "name"looseMuLowerMinusPtRelErr
    {  "type": r.TH1F, "name": "looseMuLowerPlusPtRelErr"}, #;1, "name"looseMuLowerPlusPtRelErr
    {  "type": r.TH1F, "name": "looseMuMinusDxyError"}, #;1, "name"looseMuMinusDxyError
    {  "type": r.TH1F, "name": "looseMuUpperMinusDxyError"}, #;1, "name"looseMuUpperMinusDxyError
    {  "type": r.TH1F, "name": "looseMuPlusDxyError"}, #;1, "name"looseMuPlusDxyError
    {  "type": r.TH1F, "name": "looseMuUpperPlusDxyError"}, #;1, "name"looseMuUpperPlusDxyError
    {  "type": r.TH1F, "name": "looseMuLowerMinusDxyError"}, #;1, "name"looseMuLowerMinusDxyError
    {  "type": r.TH1F, "name": "looseMuLowerPlusDxyError"}, #;1, "name"looseMuLowerPlusDxyError
    {  "type": r.TH1F, "name": "looseMuMinusDzError"}, #;1, "name"looseMuMinusDzError
    {  "type": r.TH1F, "name": "looseMuUpperMinusDzError"}, #;1, "name"looseMuUpperMinusDzError
    {  "type": r.TH1F, "name": "looseMuPlusDzError"}, #;1, "name"looseMuPlusDzError
    {  "type": r.TH1F, "name": "looseMuUpperPlusDzError"}, #;1, "name"looseMuUpperPlusDzError
    {  "type": r.TH1F, "name": "looseMuLowerMinusDzError"}, #;1, "name"looseMuLowerMinusDzError
    {  "type": r.TH1F, "name": "looseMuLowerPlusDzError"}, #;1, "name"looseMuLowerPlusDzError
    {  "type": r.TH1F, "name": "looseMuMinusPt"}, #;1, "name"looseMuMinusPt
    {  "type": r.TH1F, "name": "looseMuUpperMinusPt"}, #;1, "name"looseMuUpperMinusPt
    {  "type": r.TH1F, "name": "looseMuPlusPt"}, #;1, "name"looseMuPlusPt
    {  "type": r.TH1F, "name": "looseMuUpperPlusPt"}, #;1, "name"looseMuUpperPlusPt
    {  "type": r.TH1F, "name": "looseMuLowerMinusPt"}, #;1, "name"looseMuLowerMinusPt
    {  "type": r.TH1F, "name": "looseMuLowerPlusPt"}, #;1, "name"looseMuLowerPlusPt
    {  "type": r.TH1F, "name": "looseMuMinusEta"}, #;1, "name"looseMuMinusEta
    {  "type": r.TH1F, "name": "looseMuUpperMinusEta"}, #;1, "name"looseMuUpperMinusEta
    {  "type": r.TH1F, "name": "looseMuPlusEta"}, #;1, "name"looseMuPlusEta
    {  "type": r.TH1F, "name": "looseMuUpperPlusEta"}, #;1, "name"looseMuUpperPlusEta
    {  "type": r.TH1F, "name": "looseMuLowerMinusEta"}, #;1, "name"looseMuLowerMinusEta
    {  "type": r.TH1F, "name": "looseMuLowerPlusEta"}, #;1, "name"looseMuLowerPlusEta
    {  "type": r.TH1F, "name": "looseMuMinusPhi"}, #;1, "name"looseMuMinusPhi
    {  "type": r.TH1F, "name": "looseMuUpperMinusPhi"}, #;1, "name"looseMuUpperMinusPhi
    {  "type": r.TH1F, "name": "looseMuPlusPhi"}, #;1, "name"looseMuPlusPhi
    {  "type": r.TH1F, "name": "looseMuUpperPlusPhi"}, #;1, "name"looseMuUpperPlusPhi
    {  "type": r.TH1F, "name": "looseMuLowerMinusPhi"}, #;1, "name"looseMuLowerMinusPhi
    {  "type": r.TH1F, "name": "looseMuLowerPlusPhi"}, #;1, "name"looseMuLowerPlusPhi
    {  "type": r.TH1F, "name": "looseMuMinusTrackPt"}, #;1, "name"looseMuMinusTrackPt
    {  "type": r.TH1F, "name": "looseMuUpperMinusTrackPt"}, #;1, "name"looseMuUpperMinusTrackPt
    {  "type": r.TH1F, "name": "looseMuPlusTrackPt"}, #;1, "name"looseMuPlusTrackPt
    {  "type": r.TH1F, "name": "looseMuUpperPlusTrackPt"}, #;1, "name"looseMuUpperPlusTrackPt
    {  "type": r.TH1F, "name": "looseMuLowerMinusTrackPt"}, #;1, "name"looseMuLowerMinusTrackPt
    {  "type": r.TH1F, "name": "looseMuLowerPlusTrackPt"}, #;1, "name"looseMuLowerPlusTrackPt
    {  "type": r.TH1F, "name": "looseMuMinusTrackEta"}, #;1, "name"looseMuMinusTrackEta
    {  "type": r.TH1F, "name": "looseMuUpperMinusTrackEta"}, #;1, "name"looseMuUpperMinusTrackEta
    {  "type": r.TH1F, "name": "looseMuPlusTrackEta"}, #;1, "name"looseMuPlusTrackEta
    {  "type": r.TH1F, "name": "looseMuUpperPlusTrackEta"}, #;1, "name"looseMuUpperPlusTrackEta
    {  "type": r.TH1F, "name": "looseMuLowerMinusTrackEta"}, #;1, "name"looseMuLowerMinusTrackEta
    {  "type": r.TH1F, "name": "looseMuLowerPlusTrackEta"}, #;1, "name"looseMuLowerPlusTrackEta
    {  "type": r.TH1F, "name": "looseMuMinusTrackPhi"}, #;1, "name"looseMuMinusTrackPhi
    {  "type": r.TH1F, "name": "looseMuUpperMinusTrackPhi"}, #;1, "name"looseMuUpperMinusTrackPhi
    {  "type": r.TH1F, "name": "looseMuPlusTrackPhi"}, #;1, "name"looseMuPlusTrackPhi
    {  "type": r.TH1F, "name": "looseMuUpperPlusTrackPhi"}, #;1, "name"looseMuUpperPlusTrackPhi
    {  "type": r.TH1F, "name": "looseMuLowerMinusTrackPhi"}, #;1, "name"looseMuLowerMinusTrackPhi
    {  "type": r.TH1F, "name": "looseMuLowerPlusTrackPhi"}, #;1, "name"looseMuLowerPlusTrackPhi
    {  "type": r.TH1F, "name": "looseMuMinusTrackLayersWithMeasurement"}, #;1, "name"looseMuMinusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuUpperMinusTrackLayersWithMeasurement"}, #;1, "name"looseMuUpperMinusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuPlusTrackLayersWithMeasurement"}, #;1, "name"looseMuPlusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuUpperPlusTrackLayersWithMeasurement"}, #;1, "name"looseMuUpperPlusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuLowerMinusTrackLayersWithMeasurement"}, #;1, "name"looseMuLowerMinusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuLowerPlusTrackLayersWithMeasurement"}, #;1, "name"looseMuLowerPlusTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "looseMuMinusCurvePlusBias001"}, #;1, "name"looseMuMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuMinusCurveMinusBias001"}, #;1, "name"looseMuMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "looseMuUpperMinusCurvePlusBias001"}, #;1, "name"looseMuUpperMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuUpperMinusCurveMinusBias001"}, #;1, "name"looseMuUpperMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "looseMuLowerMinusCurvePlusBias001"}, #;1, "name"looseMuLowerMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuLowerMinusCurveMinusBias001"}, #;1, "name"looseMuLowerMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "looseMuPlusCurvePlusBias001"}, #;1, "name"looseMuPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuPlusCurveMinusBias001"}, #;1, "name"looseMuPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "looseMuUpperPlusCurvePlusBias001"}, #;1, "name"looseMuUpperPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuUpperPlusCurveMinusBias001"}, #;1, "name"looseMuUpperPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "looseMuLowerPlusCurvePlusBias001"}, #;1, "name"looseMuLowerPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "looseMuLowerPlusCurveMinusBias001"}, #;1, "name"looseMuLowerPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "TightMuonChi2"}, #;1, "name"TightMuonChi2
    {  "type": r.TH1F, "name": "UpperTightMuonChi2"}, #;1, "name"UpperTightMuonChi2
    {  "type": r.TH1F, "name": "AntiTightMuonChi2"}, #;1, "name"AntiTightMuonChi2
    {  "type": r.TH1F, "name": "UpperAntiTightMuonChi2"}, #;1, "name"UpperAntiTightMuonChi2
    {  "type": r.TH1F, "name": "LowerTightMuonChi2"}, #;1, "name"LowerTightMuonChi2
    {  "type": r.TH1F, "name": "LowerAntiTightMuonChi2"}, #;1, "name"LowerAntiTightMuonChi2
    {  "type": r.TH1F, "name": "TightMuonNdof"}, #;1, "name"TightMuonNdof
    {  "type": r.TH1F, "name": "UpperTightMuonNdof"}, #;1, "name"UpperTightMuonNdof
    {  "type": r.TH1F, "name": "AntiTightMuonNdof"}, #;1, "name"AntiTightMuonNdof
    {  "type": r.TH1F, "name": "UpperAntiTightMuonNdof"}, #;1, "name"UpperAntiTightMuonNdof
    {  "type": r.TH1F, "name": "LowerTightMuonNdof"}, #;1, "name"LowerTightMuonNdof
    {  "type": r.TH1F, "name": "LowerAntiTightMuonNdof"}, #;1, "name"LowerAntiTightMuonNdof
    {  "type": r.TH1F, "name": "TightMuonCharge"}, #;1, "name"TightMuonCharge
    {  "type": r.TH1F, "name": "UpperTightMuonCharge"}, #;1, "name"UpperTightMuonCharge
    {  "type": r.TH1F, "name": "AntiTightMuonCharge"}, #;1, "name"AntiTightMuonCharge
    {  "type": r.TH1F, "name": "UpperAntiTightMuonCharge"}, #;1, "name"UpperAntiTightMuonCharge
    {  "type": r.TH1F, "name": "LowerTightMuonCharge"}, #;1, "name"LowerTightMuonCharge
    {  "type": r.TH1F, "name": "LowerAntiTightMuonCharge"}, #;1, "name"LowerAntiTightMuonCharge
    {  "type": r.TH1F, "name": "TightMuonCurve"}, #;1, "name"TightMuonCurve
    {  "type": r.TH1F, "name": "UpperTightMuonCurve"}, #;1, "name"UpperTightMuonCurve
    {  "type": r.TH1F, "name": "AntiTightMuonCurve"}, #;1, "name"AntiTightMuonCurve
    {  "type": r.TH1F, "name": "UpperAntiTightMuonCurve"}, #;1, "name"UpperAntiTightMuonCurve
    {  "type": r.TH1F, "name": "LowerTightMuonCurve"}, #;1, "name"LowerTightMuonCurve
    {  "type": r.TH1F, "name": "LowerAntiTightMuonCurve"}, #;1, "name"LowerAntiTightMuonCurve
    {  "type": r.TH1F, "name": "TightMuonDxy"}, #;1, "name"TightMuonDxy
    {  "type": r.TH1F, "name": "UpperTightMuonDxy"}, #;1, "name"UpperTightMuonDxy
    {  "type": r.TH1F, "name": "AntiTightMuonDxy"}, #;1, "name"AntiTightMuonDxy
    {  "type": r.TH1F, "name": "UpperAntiTightMuonDxy"}, #;1, "name"UpperAntiTightMuonDxy
    {  "type": r.TH1F, "name": "LowerTightMuonDxy"}, #;1, "name"LowerTightMuonDxy
    {  "type": r.TH1F, "name": "LowerAntiTightMuonDxy"}, #;1, "name"LowerAntiTightMuonDxy
    {  "type": r.TH1F, "name": "TightMuonDz"}, #;1, "name"TightMuonDz
    {  "type": r.TH1F, "name": "UpperTightMuonDz"}, #;1, "name"UpperTightMuonDz
    {  "type": r.TH1F, "name": "AntiTightMuonDz"}, #;1, "name"AntiTightMuonDz
    {  "type": r.TH1F, "name": "UpperAntiTightMuonDz"}, #;1, "name"UpperAntiTightMuonDz
    {  "type": r.TH1F, "name": "LowerTightMuonDz"}, #;1, "name"LowerTightMuonDz
    {  "type": r.TH1F, "name": "LowerAntiTightMuonDz"}, #;1, "name"LowerAntiTightMuonDz
    {  "type": r.TH1F, "name": "TightMuonPixelHits"}, #;1, "name"TightMuonPixelHits
    {  "type": r.TH1F, "name": "UpperTightMuonPixelHits"}, #;1, "name"UpperTightMuonPixelHits
    {  "type": r.TH1F, "name": "AntiTightMuonPixelHits"}, #;1, "name"AntiTightMuonPixelHits
    {  "type": r.TH1F, "name": "UpperAntiTightMuonPixelHits"}, #;1, "name"UpperAntiTightMuonPixelHits
    {  "type": r.TH1F, "name": "LowerTightMuonPixelHits"}, #;1, "name"LowerTightMuonPixelHits
    {  "type": r.TH1F, "name": "LowerAntiTightMuonPixelHits"}, #;1, "name"LowerAntiTightMuonPixelHits
    {  "type": r.TH1F, "name": "TightMuonTrackerHits"}, #;1, "name"TightMuonTrackerHits
    {  "type": r.TH1F, "name": "UpperTightMuonTrackerHits"}, #;1, "name"UpperTightMuonTrackerHits
    {  "type": r.TH1F, "name": "AntiTightMuonTrackerHits"}, #;1, "name"AntiTightMuonTrackerHits
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTrackerHits"}, #;1, "name"UpperAntiTightMuonTrackerHits
    {  "type": r.TH1F, "name": "LowerTightMuonTrackerHits"}, #;1, "name"LowerTightMuonTrackerHits
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTrackerHits"}, #;1, "name"LowerAntiTightMuonTrackerHits
    {  "type": r.TH1F, "name": "TightMuonTightMuonStationHits"}, #;1, "name"TightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "UpperTightMuonTightMuonStationHits"}, #;1, "name"UpperTightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "AntiTightMuonTightMuonStationHits"}, #;1, "name"AntiTightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTightMuonStationHits"}, #;1, "name"UpperAntiTightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "LowerTightMuonTightMuonStationHits"}, #;1, "name"LowerTightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTightMuonStationHits"}, #;1, "name"LowerAntiTightMuonTightMuonStationHits
    {  "type": r.TH1F, "name": "TightMuonValidHits"}, #;1, "name"TightMuonValidHits
    {  "type": r.TH1F, "name": "UpperTightMuonValidHits"}, #;1, "name"UpperTightMuonValidHits
    {  "type": r.TH1F, "name": "AntiTightMuonValidHits"}, #;1, "name"AntiTightMuonValidHits
    {  "type": r.TH1F, "name": "UpperAntiTightMuonValidHits"}, #;1, "name"UpperAntiTightMuonValidHits
    {  "type": r.TH1F, "name": "LowerTightMuonValidHits"}, #;1, "name"LowerTightMuonValidHits
    {  "type": r.TH1F, "name": "LowerAntiTightMuonValidHits"}, #;1, "name"LowerAntiTightMuonValidHits
    {  "type": r.TH1F, "name": "TightMuonMatchedTightMuonStations"}, #;1, "name"TightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "UpperTightMuonMatchedTightMuonStations"}, #;1, "name"UpperTightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "AntiTightMuonMatchedTightMuonStations"}, #;1, "name"AntiTightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "UpperAntiTightMuonMatchedTightMuonStations"}, #;1, "name"UpperAntiTightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "LowerTightMuonMatchedTightMuonStations"}, #;1, "name"LowerTightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "LowerAntiTightMuonMatchedTightMuonStations"}, #;1, "name"LowerAntiTightMuonMatchedTightMuonStations
    {  "type": r.TH1F, "name": "TightMuonPtError"}, #;1, "name"TightMuonPtError
    {  "type": r.TH1F, "name": "UpperTightMuonPtError"}, #;1, "name"UpperTightMuonPtError
    {  "type": r.TH1F, "name": "AntiTightMuonPtError"}, #;1, "name"AntiTightMuonPtError
    {  "type": r.TH1F, "name": "UpperAntiTightMuonPtError"}, #;1, "name"UpperAntiTightMuonPtError
    {  "type": r.TH1F, "name": "LowerTightMuonPtError"}, #;1, "name"LowerTightMuonPtError
    {  "type": r.TH1F, "name": "LowerAntiTightMuonPtError"}, #;1, "name"LowerAntiTightMuonPtError
    {  "type": r.TH1F, "name": "TightMuonPtRelErr"}, #;1, "name"TightMuonPtRelErr
    {  "type": r.TH1F, "name": "UpperTightMuonPtRelErr"}, #;1, "name"UpperTightMuonPtRelErr
    {  "type": r.TH1F, "name": "AntiTightMuonPtRelErr"}, #;1, "name"AntiTightMuonPtRelErr
    {  "type": r.TH1F, "name": "UpperAntiTightMuonPtRelErr"}, #;1, "name"UpperAntiTightMuonPtRelErr
    {  "type": r.TH1F, "name": "LowerTightMuonPtRelErr"}, #;1, "name"LowerTightMuonPtRelErr
    {  "type": r.TH1F, "name": "LowerAntiTightMuonPtRelErr"}, #;1, "name"LowerAntiTightMuonPtRelErr
    {  "type": r.TH1F, "name": "TightMuonDxyError"}, #;1, "name"TightMuonDxyError
    {  "type": r.TH1F, "name": "UpperTightMuonDxyError"}, #;1, "name"UpperTightMuonDxyError
    {  "type": r.TH1F, "name": "AntiTightMuonDxyError"}, #;1, "name"AntiTightMuonDxyError
    {  "type": r.TH1F, "name": "UpperAntiTightMuonDxyError"}, #;1, "name"UpperAntiTightMuonDxyError
    {  "type": r.TH1F, "name": "LowerTightMuonDxyError"}, #;1, "name"LowerTightMuonDxyError
    {  "type": r.TH1F, "name": "LowerAntiTightMuonDxyError"}, #;1, "name"LowerAntiTightMuonDxyError
    {  "type": r.TH1F, "name": "TightMuonDzError"}, #;1, "name"TightMuonDzError
    {  "type": r.TH1F, "name": "UpperTightMuonDzError"}, #;1, "name"UpperTightMuonDzError
    {  "type": r.TH1F, "name": "AntiTightMuonDzError"}, #;1, "name"AntiTightMuonDzError
    {  "type": r.TH1F, "name": "UpperAntiTightMuonDzError"}, #;1, "name"UpperAntiTightMuonDzError
    {  "type": r.TH1F, "name": "LowerTightMuonDzError"}, #;1, "name"LowerTightMuonDzError
    {  "type": r.TH1F, "name": "LowerAntiTightMuonDzError"}, #;1, "name"LowerAntiTightMuonDzError
    {  "type": r.TH1F, "name": "TightMuonPt"}, #;1, "name"TightMuonPt
    {  "type": r.TH1F, "name": "UpperTightMuonPt"}, #;1, "name"UpperTightMuonPt
    {  "type": r.TH1F, "name": "AntiTightMuonPt"}, #;1, "name"AntiTightMuonPt
    {  "type": r.TH1F, "name": "UpperAntiTightMuonPt"}, #;1, "name"UpperAntiTightMuonPt
    {  "type": r.TH1F, "name": "LowerTightMuonPt"}, #;1, "name"LowerTightMuonPt
    {  "type": r.TH1F, "name": "LowerAntiTightMuonPt"}, #;1, "name"LowerAntiTightMuonPt
    {  "type": r.TH1F, "name": "TightMuonEta"}, #;1, "name"TightMuonEta
    {  "type": r.TH1F, "name": "UpperTightMuonEta"}, #;1, "name"UpperTightMuonEta
    {  "type": r.TH1F, "name": "AntiTightMuonEta"}, #;1, "name"AntiTightMuonEta
    {  "type": r.TH1F, "name": "UpperAntiTightMuonEta"}, #;1, "name"UpperAntiTightMuonEta
    {  "type": r.TH1F, "name": "LowerTightMuonEta"}, #;1, "name"LowerTightMuonEta
    {  "type": r.TH1F, "name": "LowerAntiTightMuonEta"}, #;1, "name"LowerAntiTightMuonEta
    {  "type": r.TH1F, "name": "TightMuonPhi"}, #;1, "name"TightMuonPhi
    {  "type": r.TH1F, "name": "UpperTightMuonPhi"}, #;1, "name"UpperTightMuonPhi
    {  "type": r.TH1F, "name": "AntiTightMuonPhi"}, #;1, "name"AntiTightMuonPhi
    {  "type": r.TH1F, "name": "UpperAntiTightMuonPhi"}, #;1, "name"UpperAntiTightMuonPhi
    {  "type": r.TH1F, "name": "LowerTightMuonPhi"}, #;1, "name"LowerTightMuonPhi
    {  "type": r.TH1F, "name": "LowerAntiTightMuonPhi"}, #;1, "name"LowerAntiTightMuonPhi
    {  "type": r.TH1F, "name": "TightMuonTrackPt"}, #;1, "name"TightMuonTrackPt
    {  "type": r.TH1F, "name": "UpperTightMuonTrackPt"}, #;1, "name"UpperTightMuonTrackPt
    {  "type": r.TH1F, "name": "AntiTightMuonTrackPt"}, #;1, "name"AntiTightMuonTrackPt
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTrackPt"}, #;1, "name"UpperAntiTightMuonTrackPt
    {  "type": r.TH1F, "name": "LowerTightMuonTrackPt"}, #;1, "name"LowerTightMuonTrackPt
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTrackPt"}, #;1, "name"LowerAntiTightMuonTrackPt
    {  "type": r.TH1F, "name": "TightMuonTrackEta"}, #;1, "name"TightMuonTrackEta
    {  "type": r.TH1F, "name": "UpperTightMuonTrackEta"}, #;1, "name"UpperTightMuonTrackEta
    {  "type": r.TH1F, "name": "AntiTightMuonTrackEta"}, #;1, "name"AntiTightMuonTrackEta
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTrackEta"}, #;1, "name"UpperAntiTightMuonTrackEta
    {  "type": r.TH1F, "name": "LowerTightMuonTrackEta"}, #;1, "name"LowerTightMuonTrackEta
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTrackEta"}, #;1, "name"LowerAntiTightMuonTrackEta
    {  "type": r.TH1F, "name": "TightMuonTrackPhi"}, #;1, "name"TightMuonTrackPhi
    {  "type": r.TH1F, "name": "UpperTightMuonTrackPhi"}, #;1, "name"UpperTightMuonTrackPhi
    {  "type": r.TH1F, "name": "AntiTightMuonTrackPhi"}, #;1, "name"AntiTightMuonTrackPhi
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTrackPhi"}, #;1, "name"UpperAntiTightMuonTrackPhi
    {  "type": r.TH1F, "name": "LowerTightMuonTrackPhi"}, #;1, "name"LowerTightMuonTrackPhi
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTrackPhi"}, #;1, "name"LowerAntiTightMuonTrackPhi
    {  "type": r.TH1F, "name": "TightMuonTrackLayersWithMeasurement"}, #;1, "name"TightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "UpperTightMuonTrackLayersWithMeasurement"}, #;1, "name"UpperTightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "AntiTightMuonTrackLayersWithMeasurement"}, #;1, "name"AntiTightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "UpperAntiTightMuonTrackLayersWithMeasurement"}, #;1, "name"UpperAntiTightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "LowerTightMuonTrackLayersWithMeasurement"}, #;1, "name"LowerTightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "LowerAntiTightMuonTrackLayersWithMeasurement"}, #;1, "name"LowerAntiTightMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "tightMuMinusCurvePlusBias001"}, #;1, "name"tightMuMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuMinusCurveMinusBias001"}, #;1, "name"tightMuMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "tightMuUpperMinusCurvePlusBias001"}, #;1, "name"tightMuUpperMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuUpperMinusCurveMinusBias001"}, #;1, "name"tightMuUpperMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "tightMuLowerMinusCurvePlusBias001"}, #;1, "name"tightMuLowerMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuLowerMinusCurveMinusBias001"}, #;1, "name"tightMuLowerMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "tightMuPlusCurvePlusBias001"}, #;1, "name"tightMuPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuPlusCurveMinusBias001"}, #;1, "name"tightMuPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "tightMuUpperPlusCurvePlusBias001"}, #;1, "name"tightMuUpperPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuUpperPlusCurveMinusBias001"}, #;1, "name"tightMuUpperPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "tightMuLowerPlusCurvePlusBias001"}, #;1, "name"tightMuLowerPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "tightMuLowerPlusCurveMinusBias001"}, #;1, "name"tightMuLowerPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "MuonChi2"}, #;1, "name"MuonChi2
    {  "type": r.TH1F, "name": "UpperMuonChi2"}, #;1, "name"UpperMuonChi2
    {  "type": r.TH1F, "name": "AntiMuonChi2"}, #;1, "name"AntiMuonChi2
    {  "type": r.TH1F, "name": "UpperAntiMuonChi2"}, #;1, "name"UpperAntiMuonChi2
    {  "type": r.TH1F, "name": "LowerMuonChi2"}, #;1, "name"LowerMuonChi2
    {  "type": r.TH1F, "name": "LowerAntiMuonChi2"}, #;1, "name"LowerAntiMuonChi2
    {  "type": r.TH1F, "name": "MuonNdof"}, #;1, "name"MuonNdof
    {  "type": r.TH1F, "name": "UpperMuonNdof"}, #;1, "name"UpperMuonNdof
    {  "type": r.TH1F, "name": "AntiMuonNdof"}, #;1, "name"AntiMuonNdof
    {  "type": r.TH1F, "name": "UpperAntiMuonNdof"}, #;1, "name"UpperAntiMuonNdof
    {  "type": r.TH1F, "name": "LowerMuonNdof"}, #;1, "name"LowerMuonNdof
    {  "type": r.TH1F, "name": "LowerAntiMuonNdof"}, #;1, "name"LowerAntiMuonNdof
    {  "type": r.TH1F, "name": "MuonCharge"}, #;1, "name"MuonCharge
    {  "type": r.TH1F, "name": "UpperMuonCharge"}, #;1, "name"UpperMuonCharge
    {  "type": r.TH1F, "name": "AntiMuonCharge"}, #;1, "name"AntiMuonCharge
    {  "type": r.TH1F, "name": "UpperAntiMuonCharge"}, #;1, "name"UpperAntiMuonCharge
    {  "type": r.TH1F, "name": "LowerMuonCharge"}, #;1, "name"LowerMuonCharge
    {  "type": r.TH1F, "name": "LowerAntiMuonCharge"}, #;1, "name"LowerAntiMuonCharge
    {  "type": r.TH1F, "name": "MuonCurve"}, #;1, "name"MuonCurve
    {  "type": r.TH1F, "name": "UpperMuonCurve"}, #;1, "name"UpperMuonCurve
    {  "type": r.TH1F, "name": "AntiMuonCurve"}, #;1, "name"AntiMuonCurve
    {  "type": r.TH1F, "name": "UpperAntiMuonCurve"}, #;1, "name"UpperAntiMuonCurve
    {  "type": r.TH1F, "name": "LowerMuonCurve"}, #;1, "name"LowerMuonCurve
    {  "type": r.TH1F, "name": "LowerAntiMuonCurve"}, #;1, "name"LowerAntiMuonCurve
    {  "type": r.TH1F, "name": "MuonDxy"}, #;1, "name"MuonDxy
    {  "type": r.TH1F, "name": "UpperMuonDxy"}, #;1, "name"UpperMuonDxy
    {  "type": r.TH1F, "name": "AntiMuonDxy"}, #;1, "name"AntiMuonDxy
    {  "type": r.TH1F, "name": "UpperAntiMuonDxy"}, #;1, "name"UpperAntiMuonDxy
    {  "type": r.TH1F, "name": "LowerMuonDxy"}, #;1, "name"LowerMuonDxy
    {  "type": r.TH1F, "name": "LowerAntiMuonDxy"}, #;1, "name"LowerAntiMuonDxy
    {  "type": r.TH1F, "name": "MuonDz"}, #;1, "name"MuonDz
    {  "type": r.TH1F, "name": "UpperMuonDz"}, #;1, "name"UpperMuonDz
    {  "type": r.TH1F, "name": "AntiMuonDz"}, #;1, "name"AntiMuonDz
    {  "type": r.TH1F, "name": "UpperAntiMuonDz"}, #;1, "name"UpperAntiMuonDz
    {  "type": r.TH1F, "name": "LowerMuonDz"}, #;1, "name"LowerMuonDz
    {  "type": r.TH1F, "name": "LowerAntiMuonDz"}, #;1, "name"LowerAntiMuonDz
    {  "type": r.TH1F, "name": "MuonPixelHits"}, #;1, "name"MuonPixelHits
    {  "type": r.TH1F, "name": "UpperMuonPixelHits"}, #;1, "name"UpperMuonPixelHits
    {  "type": r.TH1F, "name": "AntiMuonPixelHits"}, #;1, "name"AntiMuonPixelHits
    {  "type": r.TH1F, "name": "UpperAntiMuonPixelHits"}, #;1, "name"UpperAntiMuonPixelHits
    {  "type": r.TH1F, "name": "LowerMuonPixelHits"}, #;1, "name"LowerMuonPixelHits
    {  "type": r.TH1F, "name": "LowerAntiMuonPixelHits"}, #;1, "name"LowerAntiMuonPixelHits
    {  "type": r.TH1F, "name": "MuonTrackerHits"}, #;1, "name"MuonTrackerHits
    {  "type": r.TH1F, "name": "UpperMuonTrackerHits"}, #;1, "name"UpperMuonTrackerHits
    {  "type": r.TH1F, "name": "AntiMuonTrackerHits"}, #;1, "name"AntiMuonTrackerHits
    {  "type": r.TH1F, "name": "UpperAntiMuonTrackerHits"}, #;1, "name"UpperAntiMuonTrackerHits
    {  "type": r.TH1F, "name": "LowerMuonTrackerHits"}, #;1, "name"LowerMuonTrackerHits
    {  "type": r.TH1F, "name": "LowerAntiMuonTrackerHits"}, #;1, "name"LowerAntiMuonTrackerHits
    {  "type": r.TH1F, "name": "MuonMuonStationHits"}, #;1, "name"MuonMuonStationHits
    {  "type": r.TH1F, "name": "UpperMuonMuonStationHits"}, #;1, "name"UpperMuonMuonStationHits
    {  "type": r.TH1F, "name": "AntiMuonMuonStationHits"}, #;1, "name"AntiMuonMuonStationHits
    {  "type": r.TH1F, "name": "UpperAntiMuonMuonStationHits"}, #;1, "name"UpperAntiMuonMuonStationHits
    {  "type": r.TH1F, "name": "LowerMuonMuonStationHits"}, #;1, "name"LowerMuonMuonStationHits
    {  "type": r.TH1F, "name": "LowerAntiMuonMuonStationHits"}, #;1, "name"LowerAntiMuonMuonStationHits
    {  "type": r.TH1F, "name": "MuonValidHits"}, #;1, "name"MuonValidHits
    {  "type": r.TH1F, "name": "UpperMuonValidHits"}, #;1, "name"UpperMuonValidHits
    {  "type": r.TH1F, "name": "AntiMuonValidHits"}, #;1, "name"AntiMuonValidHits
    {  "type": r.TH1F, "name": "UpperAntiMuonValidHits"}, #;1, "name"UpperAntiMuonValidHits
    {  "type": r.TH1F, "name": "LowerMuonValidHits"}, #;1, "name"LowerMuonValidHits
    {  "type": r.TH1F, "name": "LowerAntiMuonValidHits"}, #;1, "name"LowerAntiMuonValidHits
    {  "type": r.TH1F, "name": "MuonMatchedMuonStations"}, #;1, "name"MuonMatchedMuonStations
    {  "type": r.TH1F, "name": "UpperMuonMatchedMuonStations"}, #;1, "name"UpperMuonMatchedMuonStations
    {  "type": r.TH1F, "name": "AntiMuonMatchedMuonStations"}, #;1, "name"AntiMuonMatchedMuonStations
    {  "type": r.TH1F, "name": "UpperAntiMuonMatchedMuonStations"}, #;1, "name"UpperAntiMuonMatchedMuonStations
    {  "type": r.TH1F, "name": "LowerMuonMatchedMuonStations"}, #;1, "name"LowerMuonMatchedMuonStations
    {  "type": r.TH1F, "name": "LowerAntiMuonMatchedMuonStations"}, #;1, "name"LowerAntiMuonMatchedMuonStations
    {  "type": r.TH1F, "name": "MuonPtError"}, #;1, "name"MuonPtError
    {  "type": r.TH1F, "name": "UpperMuonPtError"}, #;1, "name"UpperMuonPtError
    {  "type": r.TH1F, "name": "AntiMuonPtError"}, #;1, "name"AntiMuonPtError
    {  "type": r.TH1F, "name": "UpperAntiMuonPtError"}, #;1, "name"UpperAntiMuonPtError
    {  "type": r.TH1F, "name": "LowerMuonPtError"}, #;1, "name"LowerMuonPtError
    {  "type": r.TH1F, "name": "LowerAntiMuonPtError"}, #;1, "name"LowerAntiMuonPtError
    {  "type": r.TH1F, "name": "MuonPtRelErr"}, #;1, "name"MuonPtRelErr
    {  "type": r.TH1F, "name": "UpperMuonPtRelErr"}, #;1, "name"UpperMuonPtRelErr
    {  "type": r.TH1F, "name": "AntiMuonPtRelErr"}, #;1, "name"AntiMuonPtRelErr
    {  "type": r.TH1F, "name": "UpperAntiMuonPtRelErr"}, #;1, "name"UpperAntiMuonPtRelErr
    {  "type": r.TH1F, "name": "LowerMuonPtRelErr"}, #;1, "name"LowerMuonPtRelErr
    {  "type": r.TH1F, "name": "LowerAntiMuonPtRelErr"}, #;1, "name"LowerAntiMuonPtRelErr
    {  "type": r.TH1F, "name": "MuonDxyError"}, #;1, "name"MuonDxyError
    {  "type": r.TH1F, "name": "UpperMuonDxyError"}, #;1, "name"UpperMuonDxyError
    {  "type": r.TH1F, "name": "AntiMuonDxyError"}, #;1, "name"AntiMuonDxyError
    {  "type": r.TH1F, "name": "UpperAntiMuonDxyError"}, #;1, "name"UpperAntiMuonDxyError
    {  "type": r.TH1F, "name": "LowerMuonDxyError"}, #;1, "name"LowerMuonDxyError
    {  "type": r.TH1F, "name": "LowerAntiMuonDxyError"}, #;1, "name"LowerAntiMuonDxyError
    {  "type": r.TH1F, "name": "MuonDzError"}, #;1, "name"MuonDzError
    {  "type": r.TH1F, "name": "UpperMuonDzError"}, #;1, "name"UpperMuonDzError
    {  "type": r.TH1F, "name": "AntiMuonDzError"}, #;1, "name"AntiMuonDzError
    {  "type": r.TH1F, "name": "UpperAntiMuonDzError"}, #;1, "name"UpperAntiMuonDzError
    {  "type": r.TH1F, "name": "LowerMuonDzError"}, #;1, "name"LowerMuonDzError
    {  "type": r.TH1F, "name": "LowerAntiMuonDzError"}, #;1, "name"LowerAntiMuonDzError
    {  "type": r.TH1F, "name": "MuonPt"}, #;1, "name"MuonPt
    {  "type": r.TH1F, "name": "UpperMuonPt"}, #;1, "name"UpperMuonPt
    {  "type": r.TH1F, "name": "AntiMuonPt"}, #;1, "name"AntiMuonPt
    {  "type": r.TH1F, "name": "UpperAntiMuonPt"}, #;1, "name"UpperAntiMuonPt
    {  "type": r.TH1F, "name": "LowerMuonPt"}, #;1, "name"LowerMuonPt
    {  "type": r.TH1F, "name": "LowerAntiMuonPt"}, #;1, "name"LowerAntiMuonPt
    {  "type": r.TH1F, "name": "MuonEta"}, #;1, "name"MuonEta
    {  "type": r.TH1F, "name": "UpperMuonEta"}, #;1, "name"UpperMuonEta
    {  "type": r.TH1F, "name": "AntiMuonEta"}, #;1, "name"AntiMuonEta
    {  "type": r.TH1F, "name": "UpperAntiMuonEta"}, #;1, "name"UpperAntiMuonEta
    {  "type": r.TH1F, "name": "LowerMuonEta"}, #;1, "name"LowerMuonEta
    {  "type": r.TH1F, "name": "LowerAntiMuonEta"}, #;1, "name"LowerAntiMuonEta
    {  "type": r.TH1F, "name": "MuonPhi"}, #;1, "name"MuonPhi
    {  "type": r.TH1F, "name": "UpperMuonPhi"}, #;1, "name"UpperMuonPhi
    {  "type": r.TH1F, "name": "AntiMuonPhi"}, #;1, "name"AntiMuonPhi
    {  "type": r.TH1F, "name": "UpperAntiMuonPhi"}, #;1, "name"UpperAntiMuonPhi
    {  "type": r.TH1F, "name": "LowerMuonPhi"}, #;1, "name"LowerMuonPhi
    {  "type": r.TH1F, "name": "LowerAntiMuonPhi"}, #;1, "name"LowerAntiMuonPhi
    {  "type": r.TH1F, "name": "MuonTrackPt"}, #;1, "name"MuonTrackPt
    {  "type": r.TH1F, "name": "UpperMuonTrackPt"}, #;1, "name"UpperMuonTrackPt
    {  "type": r.TH1F, "name": "AntiMuonTrackPt"}, #;1, "name"AntiMuonTrackPt
    {  "type": r.TH1F, "name": "UpperAntiMuonTrackPt"}, #;1, "name"UpperAntiMuonTrackPt
    {  "type": r.TH1F, "name": "LowerMuonTrackPt"}, #;1, "name"LowerMuonTrackPt
    {  "type": r.TH1F, "name": "LowerAntiMuonTrackPt"}, #;1, "name"LowerAntiMuonTrackPt
    {  "type": r.TH1F, "name": "MuonTrackEta"}, #;1, "name"MuonTrackEta
    {  "type": r.TH1F, "name": "UpperMuonTrackEta"}, #;1, "name"UpperMuonTrackEta
    {  "type": r.TH1F, "name": "AntiMuonTrackEta"}, #;1, "name"AntiMuonTrackEta
    {  "type": r.TH1F, "name": "UpperAntiMuonTrackEta"}, #;1, "name"UpperAntiMuonTrackEta
    {  "type": r.TH1F, "name": "LowerMuonTrackEta"}, #;1, "name"LowerMuonTrackEta
    {  "type": r.TH1F, "name": "LowerAntiMuonTrackEta"}, #;1, "name"LowerAntiMuonTrackEta
    {  "type": r.TH1F, "name": "MuonTrackPhi"}, #;1, "name"MuonTrackPhi
    {  "type": r.TH1F, "name": "UpperMuonTrackPhi"}, #;1, "name"UpperMuonTrackPhi
    {  "type": r.TH1F, "name": "AntiMuonTrackPhi"}, #;1, "name"AntiMuonTrackPhi
    {  "type": r.TH1F, "name": "UpperAntiMuonTrackPhi"}, #;1, "name"UpperAntiMuonTrackPhi
    {  "type": r.TH1F, "name": "LowerMuonTrackPhi"}, #;1, "name"LowerMuonTrackPhi
    {  "type": r.TH1F, "name": "LowerAntiMuonTrackPhi"}, #;1, "name"LowerAntiMuonTrackPhi
    {  "type": r.TH1F, "name": "MuonTrackLayersWithMeasurement"}, #;1, "name"MuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "UpperMuonTrackLayersWithMeasurement"}, #;1, "name"UpperMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "AntiMuonTrackLayersWithMeasurement"}, #;1, "name"AntiMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "UpperAntiMuonTrackLayersWithMeasurement"}, #;1, "name"UpperAntiMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "LowerMuonTrackLayersWithMeasurement"}, #;1, "name"LowerMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "LowerAntiMuonTrackLayersWithMeasurement"}, #;1, "name"LowerAntiMuonTrackLayersWithMeasurement
    {  "type": r.TH1F, "name": "muMinusCurvePlusBias001"}, #;1, "name"muMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "muMinusCurveMinusBias001"}, #;1, "name"muMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "muUpperMinusCurvePlusBias001"}, #;1, "name"muUpperMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "muUpperMinusCurveMinusBias001"}, #;1, "name"muUpperMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "muLowerMinusCurvePlusBias001"}, #;1, "name"muLowerMinusCurvePlusBias001
    {  "type": r.TH1F, "name": "muLowerMinusCurveMinusBias001"}, #;1, "name"muLowerMinusCurveMinusBias001
    {  "type": r.TH1F, "name": "muPlusCurvePlusBias001"}, #;1, "name"muPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "muPlusCurveMinusBias001"}, #;1, "name"muPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "muUpperPlusCurvePlusBias001"}, #;1, "name"muUpperPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "muUpperPlusCurveMinusBias001"}, #;1, "name"muUpperPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "muLowerPlusCurvePlusBias001"}, #;1, "name"muLowerPlusCurvePlusBias001
    {  "type": r.TH1F, "name": "muLowerPlusCurveMinusBias001"}, #;1, "name"muLowerPlusCurveMinusBias001
    {  "type": r.TH1F, "name": "upperChi2"}, #;1, "name"upperChi2
    {  "type": r.TH1F, "name": "upperNdof"}, #;1, "name"upperNdof
    {  "type": r.TH1F, "name": "upperCharge"}, #;1, "name"upperCharge
    {  "type": r.TH1F, "name": "upperCurve"}, #;1, "name"upperCurve
    {  "type": r.TH1F, "name": "upperDxy"}, #;1, "name"upperDxy
    {  "type": r.TH1F, "name": "upperDz"}, #;1, "name"upperDz
    {  "type": r.TH1F, "name": "upperPixelHits"}, #;1, "name"upperPixelHits
    {  "type": r.TH1F, "name": "upperTrackerHits"}, #;1, "name"upperTrackerHits
    {  "type": r.TH1F, "name": "upperMuonStationHits"}, #;1, "name"upperMuonStationHits
    {  "type": r.TH1F, "name": "upperValidHits"}, #;1, "name"upperValidHits
    {  "type": r.TH1F, "name": "upperMatchedMuonStation"}, #;1, "name"upperMatchedMuonStations
    {  "type": r.TH1F, "name": "upperPtError"}, #;1, "name"upperPtError
    {  "type": r.TH1F, "name": "upperPtRelErr"}, #;1, "name"upperPtRelErr
    {  "type": r.TH1F, "name": "upperDxyError"}, #;1, "name"upperDxyError
    {  "type": r.TH1F, "name": "upperDzError"}, #;1, "name"upperDzError
    {  "type": r.TH1F, "name": "upperPt"}, #;1, "name"upperPt
    {  "type": r.TH1F, "name": "upperEta"}, #;1, "name"upperEta
    {  "type": r.TH1F, "name": "upperPhi"}, #;1, "name"upperPhi
    {  "type": r.TH1F, "name": "upperTrackPt"}, #;1, "name"upperTrackPt
    {  "type": r.TH1F, "name": "upperTrackEta"}, #;1, "name"upperTrackEta
    {  "type": r.TH1F, "name": "upperTrackPhi"}, #;1, "name"upperTrackPhi
    {  "type": r.TH1F, "name": "upperTrackerLayersWithMeasurement"}, #;1, "name"upperTrackerLayersWithMeasurement
    {  "type": r.TH1F, "name": "upperCurvePlusBias001"}, #;1, "name"upperCurvePlusBias001
    {  "type": r.TH1F, "name": "upperCurveMinusBias001"}, #;1, "name"upperCurveMinusBias001
    {  "type": r.TH1F, "name": "lowerChi2"}, #;1, "name"lowerChi2
    {  "type": r.TH1F, "name": "lowerNdof"}, #;1, "name"lowerNdof
    {  "type": r.TH1F, "name": "lowerCharge"}, #;1, "name"lowerCharge
    {  "type": r.TH1F, "name": "lowerCurve"}, #;1, "name"lowerCurve
    {  "type": r.TH1F, "name": "lowerDxy"}, #;1, "name"lowerDxy
    {  "type": r.TH1F, "name": "lowerDz"}, #;1, "name"lowerDz
    {  "type": r.TH1F, "name": "lowerPixelHits"}, #;1, "name"lowerPixelHits
    {  "type": r.TH1F, "name": "lowerTrackerHits"}, #;1, "name"lowerTrackerHits
    {  "type": r.TH1F, "name": "lowerMuonStationHits"}, #;1, "name"lowerMuonStationHits
    {  "type": r.TH1F, "name": "lowerValidHits"}, #;1, "name"lowerValidHits
    {  "type": r.TH1F, "name": "lowerMatchedMuonStation"}, #;1, "name"lowerMatchedMuonStations
    {  "type": r.TH1F, "name": "lowerPtError"}, #;1, "name"lowerPtError
    {  "type": r.TH1F, "name": "lowerPtRelErr"}, #;1, "name"lowerPtRelErr
    {  "type": r.TH1F, "name": "lowerDxyError"}, #;1, "name"lowerDxyError
    {  "type": r.TH1F, "name": "lowerDzError"}, #;1, "name"lowerDzError
    {  "type": r.TH1F, "name": "lowerPt"}, #;1, "name"lowerPt
    {  "type": r.TH1F, "name": "lowerEta"}, #;1, "name"lowerEta
    {  "type": r.TH1F, "name": "lowerPhi"}, #;1, "name"lowerPhi
    {  "type": r.TH1F, "name": "lowerTrackPt"}, #;1, "name"lowerTrackPt
    {  "type": r.TH1F, "name": "lowerTrackEta"}, #;1, "name"lowerTrackEta
    {  "type": r.TH1F, "name": "lowerTrackPhi"}, #;1, "name"lowerTrackPhi
    {  "type": r.TH1F, "name": "lowerTrackerLayersWithMeasurement"}, #;1, "name"lowerTrackerLayersWithMeasurement
    {  "type": r.TH1F, "name": "lowerCurvePlusBias001"}, 
    {  "type": r.TH1F, "name": "lowerCurveMinusBias001"},
]
